
CREATE TABLE MOVIE
(
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(128) NOT NULL,
  YEAR_RELEASED INT,
  DATE_RELEASED DATE,
  RATING_ID MEDIUMINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (RATING_ID) REFERENCES MOVIE_RATING (ID)
); 

CREATE TABLE MOVIE_RATING
(
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(10),
  DESCRIPTION VARCHAR(256),
  PRIMARY KEY (ID)
);

CREATE TABLE GENRE
(
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE CREW_ROLE
(
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE MOVIE_INFO
(
  ID INT NOT NULL AUTO_INCREMENT,
  RATING DECIMAL(2,1) NOT NULL,
  IMAGE_LINK VARCHAR(256),
  PLOT VARCHAR(500),
  RANK MEDIUMINT,
  RUNNING_TIME INT,
  PRIMARY KEY (ID)
); 

CREATE TABLE MOVIE_GENRE
(
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  MOVIE_ID INT,
  GENRE_ID MEDIUMINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);

CREATE TABLE CREW
(
  ID INT NOT NULL AUTO_INCREMENT,
  FULL_NAME VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE MOVIE_CREW
(
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  MOVIE_ID INT,
  CREW_ROLE_ID MEDIUMINT,
  CREW_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID),
  FOREIGN KEY (CREW_ROLE_ID) REFERENCES CREW_ROLE (ID),
  FOREIGN KEY (CREW_ID) REFERENCES CREW (ID)
);

